---
services:
  appservice:
    image: vamsikrishnakakani/test-repo:javaimage
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    deploy:
      replicas: 3
    networks:
      - mynetwork

  devopsdb:
    image: vamsikrishnakakani/test-repo:dbimage
    ports:
      - "3306:3306"
    volumes:
      - userdata:/var/lib/mysql
    deploy:
      replicas: 1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay

volumes:
  userdata:
